/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ThemeConfig, ThemePreset } from '../types/circuit';

export const THEME_PRESETS: Record<ThemePreset, ThemeConfig> = {
  emerald: {
    id: 'emerald',
    name: 'Matrix Emerald (Default)',
    description: 'Vibrant cyberpunk neon emerald with deep digital dark background.',
    primaryColor: '#10b981',
    secondaryColor: '#34d399',
    accentColor: '#059669',
    wireHighColor: '#10b981',
    wireGlowColor: 'rgba(16, 185, 129, 0.45)',
    canvasBg: '#080d1a',
    panelBg: '#0b111e',
    borderTone: 'rgba(16, 185, 129, 0.25)',
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyberpunk Neon',
    description: 'Electric cyan and neon magenta futuristic synthwave aesthetic.',
    primaryColor: '#06b6d4',
    secondaryColor: '#ec4899',
    accentColor: '#8b5cf6',
    wireHighColor: '#00f2fe',
    wireGlowColor: 'rgba(6, 182, 212, 0.5)',
    canvasBg: '#090a14',
    panelBg: '#0e101f',
    borderTone: 'rgba(6, 182, 212, 0.3)',
  },
  cobalt: {
    id: 'cobalt',
    name: 'Electric Cobalt',
    description: 'Deep navy oceanic dark paired with high-voltage sapphire blue traces.',
    primaryColor: '#3b82f6',
    secondaryColor: '#60a5fa',
    accentColor: '#2563eb',
    wireHighColor: '#38bdf8',
    wireGlowColor: 'rgba(56, 189, 248, 0.5)',
    canvasBg: '#070e1e',
    panelBg: '#0a142c',
    borderTone: 'rgba(59, 130, 246, 0.3)',
  },
  amber: {
    id: 'amber',
    name: 'Amber Phosphor (Retro CRT)',
    description: 'Warm glowing amber gold evoking vintage vacuum tube computers.',
    primaryColor: '#f59e0b',
    secondaryColor: '#fbbf24',
    accentColor: '#d97706',
    wireHighColor: '#fbbf24',
    wireGlowColor: 'rgba(245, 158, 11, 0.45)',
    canvasBg: '#100d07',
    panelBg: '#18130a',
    borderTone: 'rgba(245, 158, 11, 0.3)',
  },
  crimson: {
    id: 'crimson',
    name: 'Crimson Nova',
    description: 'Intense laser red and glowing ruby accents for high-energy labs.',
    primaryColor: '#f43f5e',
    secondaryColor: '#fb7185',
    accentColor: '#e11d48',
    wireHighColor: '#ff2a5f',
    wireGlowColor: 'rgba(244, 63, 94, 0.5)',
    canvasBg: '#13080b',
    panelBg: '#1c0c11',
    borderTone: 'rgba(244, 63, 94, 0.3)',
  },
  violet: {
    id: 'violet',
    name: 'Deep Amethyst',
    description: 'Space nebula purple and violet logic lines with stellar backdrop.',
    primaryColor: '#a855f7',
    secondaryColor: '#c084fc',
    accentColor: '#9333ea',
    wireHighColor: '#d8b4fe',
    wireGlowColor: 'rgba(168, 85, 247, 0.5)',
    canvasBg: '#0d0818',
    panelBg: '#140c24',
    borderTone: 'rgba(168, 85, 247, 0.3)',
  },
  monochrome: {
    id: 'monochrome',
    name: 'Monochrome Slate',
    description: 'Minimalist high-contrast obsidian slate with crisp pure white logic paths.',
    primaryColor: '#e2e8f0',
    secondaryColor: '#94a3b8',
    accentColor: '#64748b',
    wireHighColor: '#ffffff',
    wireGlowColor: 'rgba(255, 255, 255, 0.4)',
    canvasBg: '#0a0d14',
    panelBg: '#0f131d',
    borderTone: 'rgba(148, 163, 184, 0.25)',
  },
};
